name: gui_tracks
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.0
  - pip
  - pip:
    - opencv-python
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - tk
  - pandas

