name: msp
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.0
  - pip
  - pip:
    - opencv-python
    - trackpy==0.4.2
    - pgmpy==0.1.9
    - tqdm
    - torch==1.0.1
    - scikit-learn==0.20.3
  - numpy
  - scipy==1.5.2
  - matplotlib==3.3.2
  - scikit-image==0.17.2
  - tk
  - pandas
  - keras==2.3.1
  - joblib==0.14.1
  

