name: gui_tracks
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6.8
  - pip
  - pip:
    - opencv-python
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - tk

