name: msp
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.0
  - pip
  - pip:
    - opencv-python==4.1.0.25
    - trackpy==0.4.2
    - pgmpy==0.1.9
    - tqdm==4.43.0
    - scikit-learn==0.20.3
  - pytorch-cpu==1.0.1
  - numpy==1.18.1
  - scipy==1.5.0
  - matplotlib==3.1.3
  - scikit-image==0.16.2
  - tk==8.6.8
  - pandas==1.0.3
  - keras==2.3.1
  - joblib==0.14.1
  - tensorflow==2.1.0
  



